config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root 'homes#top'
  get 'homes/ranking' => 'homes#ranking'
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
  end
  resources :dogs
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :follows_index, on: :member
  end
  get 'search' => "searches#search"
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord

  validates :comment, presence: true, length: { maximum: 200 }

  belongs_to :user
  belongs_to :article
end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  

  def create
    @article = Article.find(params[:article_id])
    @comment = current_user.article_comments.new(article_comment_params)
    @comment.article_id = @article.id
    if @comment.save
      #redirect_to article_path(article)　非同期通信
    else
      render 'show'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = ArticleComment.find(params[:id])
    @comment.destroy
    #redirect_to article_path(params[:article_id])　非同期通信
  end

  private

  def article_comment_params
    params.require(:article_comment).permit(:comment)
  end

end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/views/article_comments/_article_comment.html.erb
<% article_comments.each do |article_comment| %>
  <tr>
    <td>
      <%= link_to user_path(article_comment.user) do %>
        <%= attachment_image_tag article_comment.user, :image, fallback: "no_image.jpg" ,class: "img4" %><br />
        <%= link_to article_comment.user.name %>
      <% end %>
      <%= article_comment.created_at.strftime('%Y/%m/%d') %>
    </td>
    <td>
      <%= article_comment.comment %>
    </td>
    <td>
      <% if article_comment.user == current_user || current_user.admin %>
        <%= link_to "削除", article_article_comment_path(article_comment.article, article_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/article_comments/_comment_count.html.erb
コメント件数：<%= article_comments.count %>

app/views/article_comments/create.js.erb
$("#comments_area").html("<%= j(render 'article_comments/article_comment', { article_comments: @comment.article.article_comments }) %>");
$("textarea").val('');
$("#comment-count").html("<%= j(render "article_comments/comment_count", article_comments: @article.article_comments) %>");

app/views/article_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'article_comments/article_comment', { article_comments: @comment.article.article_comments }) %>");
$("textarea").val('');
$("#comment-count").html("<%= j(render "article_comments/comment_count", article_comments: @article.article_comments) %>");