config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root 'homes#top'
  get 'homes/ranking' => 'homes#ranking'
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
  end
  resources :dogs
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :follows_index, on: :member
  end
  get 'search' => "searches#search"
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 15 }
  validates :introduction, length: { maximum: 200 }


  has_many :dogs, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :article_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following


  attachment :image

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end



  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?", "%#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: [:edit, :unsubscribe]

  def index
    @users = User.all.page(params[:page]).per(5) #5件表示それ以上は無限スクロールで表示
    @dog = Dog.new
    @dogs = Dog.all
  end

  def show
    @user = User.find(params[:id])
    @dogs = @user.dogs
    @dog = Dog.new
    @articles = @user.articles.page(params[:page]).per(6) #マイページにて投稿を表示6件以上は無限スクロール
  end

  def edit
    @user = User.find(params[:id])
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def follows_index
    @article = Article.limit(30).order(" created_at DESC ") #30件まで新着順で表示
    @articles = @article.where(user_id: [*current_user.following_ids]).page(params[:page]).per(8) #8件表示それ以上は無限スクロールで表示
  end

  def follows
    @user = User.find(params[:id])
    @follows = @user.followings.page(params[:page]).per(5)#5件表示それ以上は無限スクロールで表示
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(5) #5件表示それ以上は無限スクロールで表示
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to :root #削除に成功すればrootページに戻る
  end

   private

  def user_params
    params.require(:user).permit(:name, :image, :introduction, :admin, :is_deleted)
  end

  def baria_user
    @user = User.find(params[:id])
      unless @user.id == current_user.id || current_user.admin
        #本人の他に管理者フラグを持っている人も編集可能
        redirect_to current_user
      end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if current_user != user %>
  <% if user.followed_by?(current_user) %>
    <%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-success btn-sm btn-block follow" %>
  <% else %>
    <%=link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-info btn-sm btn-block follow" %>
  <% end %>
<% end %>

app/views/users/_follow_count.html.erb
<%= user.followers.count %>人

app/views/users/_user_base.html.erb
<h2>アカウント情報</h2>
<%= attachment_image_tag user, :image, fallback: "no_image.jpg", class: "center mx-auto" %>
<table class="table info text-break">
  <tbody>
    <tr>
      <th colspan="2">名前<br />
        <%= user.name %>
      </th>
    </tr>
    <tr>
      <th colspan="2">愛犬<br />
        <% user.dogs.each do |dog| %>
          <i class="fas fa-dog"></i><%= dog.name %>(<%= dog.dog_type_id %>)<br />
        <% end %>
      </th>
    </tr>
    <tr>
      <th colspan="2">自己紹介<br />
        <%= user.introduction %>
      </th>
    </tr>
    <tr>
      <th>
        <%=link_to "フォロー", follows_user_path(user.id) %><br />
        <%= user.followings.count %>人
      </th>
      <th>
        <%=link_to "フォロワー", followers_user_path(user.id) %>
        <div id="follow_counts_<%= user.id %>">
          <%= render "follow_count", user: user %>
        </div>
      </th>
    </tr>
    <% if user == current_user %>
      <tr>
        <th colspan="2">
          <%=link_to "フォローユーザー新着投稿", follows_index_user_path(user.id) %><br />
        </th>
      </tr>
    <% end %>
  </tbody>
</table>
  <% if current_user.admin? %>
    <div id="follow_buttons_<%= user.id %>">
      <%= render "follow", user: user %>
    </div>
    <div class="admin-info">
      <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  <% elsif user == current_user %>
    <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
    <%= link_to "犬を登録",new_dog_path,class: "btn btn-success btn-sm btn-block mb-3 new_dog" %>
    <%= link_to "記事を投稿",new_article_path,class: "btn btn-primary btn-sm btn-block new_article" %>
  <% else %>
    <div id="follow_buttons_<%= user.id %>">
      <%= render "follow", user: user %>
    </div>
  <% end %>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :image, :fill, 60, 60, fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <% user.dogs.each do |dog| %>
      <tr>
        <th>pet_dogs</th>
        <th><%= dog.name %></th>
      </tr>
    <% end %>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <%= render 'devise/shared/error_messages', resource: @user %>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-5 px-sm-0 mx-auto">
      <h1 class="font-size1">ユーザー編集画面</h1>
      <%= form_with model:@user, local: true do |f| %>
        <div cass="form">
          <div class="form-group">
            <label for="user name">
              名前
              <em>必須</em>
            </label>（１５文字以内）<br />
            <%= f.text_field :name %>
          </div>
          <h4 class="img-select">プロフィール写真を選択する</h4>
          <div class="form-group">
            <%= attachment_image_tag(@user, :image, :fill,100,100, fallback: "no_image.jpg",size:"100x100",id:"preview_0") %>
            <%= f.attachment_field :image %>
            <script>
              $('#user_image').on('change', function (e) {
                var reader = new FileReader();
                reader.onload = function (e) {
                  $("#preview_0").attr('src', e.target.result);
                }
                reader.readAsDataURL(e.target.files[0]);
              });
            </script>
          </div>
          <div class="form-group">
            <label for="user introduction">自己紹介</label>（２００文字以内）
            <%= f.text_area :introduction, size:'90x5' %>
          </div>
          <div class="form-group">
            <%= f.submit '変更する' %>
            <div class="text-center taikai">
               <%= link_to "退会する",unsubscribe_path(@user),class:"btn btn-danger" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container-xl-12">
  <div class="row">
    <h2 class="mx-auto follow-name"><%= @user.name %>さんのフォローワー一覧</h2>
    <div class="col-md-12 user-index">
      <% if @followers.empty? %>
        <h1 class="not-user">ユーザーがいません</h1>
      <% else %>
        <div class="scroll-list jscroll">
          <% @followers.each do |follower| %>
            <ul class="align-items-center center2">
              <li class="follow-catalog">
                <%= link_to user_path(follower.id) do %>
                  <%= attachment_image_tag follower, :image, fallback: "no_image.jpg", class: "text-center img2" %>
                <% end %>
              </li>
              <li class="follow-catalog abridgement4">
                名前：
                <%= link_to follower.name, user_path(follower.id) %>
              </li>
              <li class="follow-catalog">
                dog：
                <%= follower.dogs.count %>匹
              </li>
              <li class="follow-catalog">
                投稿：
                <%= follower.articles.count %>本
              </li>
            </ul>
          <% end %>
          <%= paginate @followers %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container-xl-12">
  <div class="row">
    <h2 class="mx-auto follow-name"><%= @user.name %>さんのフォロー一覧</h2>
    <div class="col-md-12 user-index">
      <% if @follows.empty? %>
        <h1 class="not-user">ユーザーがいません</h1>
      <% else %>
        <div class="scroll-list jscroll">
          <% @follows.each do |following| %>
            <ul class="align-items-center center2">
              <li class="follow-catalog">
                <%= link_to user_path(following.id) do %>
                  <%= attachment_image_tag following, :image, fallback: "no_image.jpg", class: "text-center img2" %>
                <% end %>
              </li>
              <li class="follow-catalog abridgement4">
                名前：
                <%= link_to following.name, user_path(following.id) %>
              </li>
              <li class="follow-catalog">
                dog：
                <%= following.dogs.count %>匹
              </li>
              <li class="follow-catalog">
                投稿：
                <%= following.articles.count %>本
              </li>
            </ul>
          <% end %>
          <%= paginate @follows %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows_index.html.erb
<div class="container">
  <h3>フォロー新着投稿(30件)</h3>
  <% if @articles.empty? %>
    <h1 class="not-user">まだ投稿がありません</h1>
  <% else %>
    <div class="scroll-list jscroll">
      <div class="row row-cols-1 row-cols-md-4 mx-auto">
        <% @articles.each.with_index(1) do |article, i| %>
          <div class="col mb-4">
            <div class="card">
              <div class="abridgement">
                タイトル<br /><%= link_to article.title,article_path(article.id) %>
              </div>
              <p><%= "#{article.article_comments.count} コメント" %></p>
              <%= link_to article_path(article.id) do %>
                <%= attachment_image_tag(article, :image1,fallback: "no_image.jpg",class: 'article-img' ) %><br />
                <div class="abridgement">
                  投稿者 <%= article.user.name %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= paginate @articles %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container-xl-12">
  <div class="row mx-auto">
    <h2 class="offset-1">ユーザー一覧</h2>
    <div class="col-md-12 user-index">
      <div class="scroll-list jscroll">
        <% @users.each do |user| %>
          <ul class=" align-items-center center2">
            <li class="user-catalog">
              <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :image, fallback: "no_image.jpg",class: "text-center img2" %>
              <% end %>
            </li>
            <li class="user-catalog abridgement3">
              名前<br />
              <%= link_to user.name, user_path(user.id) %>
            </li>

            <li class="user-catalog">
              dog<br />
              <%= user.dogs.count %>匹
            </li>
            <li class="user-catalog">
              投稿<br />
              <%= user.articles.count %>本
            </li>
            <div class="user-catalog">
              フォロワー<br />
              <li id="follow_counts_<%= user.id %>">
                <%= render "follow_count", user: user %>
              </li>
            </div>
            <div class="user-catalog">
              <% if user == current_user %>
                <li>myアカウント</li>
              <% else %>
                <li id="follow_buttons_<%= user.id %>">
                  <%= render "follow", user: user %>
                </li>
              <% end %>
            </div>
          </ul>
        <% end %>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <%= render 'user_base', user: @user %>
    </div>
    <div class="col-md-7 offset-md-1">
      <h2>Pet dogs</h2>
      <table class="table-hover table3">
        <thead>
          <tr class="center2">
            <th></th>
            <th>犬種</th>
            <th>名前</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @dogs.each do |dog| %>
            <tr class="center2">
              <td>
                <%= link_to dog_path(dog.id) do %>
                  <%= attachment_image_tag(dog, :image1, fallback: "no_image.jpg",class: "img5") %>
                <% end %>
              </td>
              <td>
                <%= dog.dog_type_id %>
              </td>
              <td>
                <%= link_to dog.name, dog_path(dog) %>
              </td>
              <td colspan="3"></td>
            </tr>
         <% end %>
        </tbody>
      </table>
      <h3>投稿一覧</h3>
      <div class="scroll-list jscroll">
        <div class="row row-cols-1 row-cols-md-3">
          <% @articles.each do |article| %>
            <div class="col mb-4">
              <div class="card">
                <div class="abridgement">
                  <p>タイトル<br />
                    <%= link_to article.title,article_path(article.id) %>
                  </p>
                </div>
                <%= link_to article_path(article.id) do %>
                  <%= attachment_image_tag(article, :image1, :fill, 170, 170, fallback: "no_image.jpg",class: 'article-img' ) %><br />
                <% end %>
              </div>
              <table>
                <div id="favorite_buttons_<%= article.id %>">
                  <%= render "favorites/favorite", article: article %>
                </div>
                コメント件数：<%= article.article_comments.count %>
              </table>
            </div>
          <% end %>
          <%= paginate @articles %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h5 class="font-weight-bold text-center mb-7">本当に退会しますか？</h5>
      <p class="text-center"><br />再度ご利用をいただく場合には<br />新規登録のお手続きが必要になります。</p>
      <p class="text-center"><br />退会する場合は<br />「退会する」をクリックしてください。</p>
      <div class="text-center">
        <%= link_to "退会しない", user_path(current_user), class: "btn btn-primary mx-5" %>
        <%= link_to "退会する", user_path(@user), method: :delete, data: { confilm: "本当に退会しますか？" }, class: "btn btn-danger mx-5" %>
      </div>
    </div>
  </div>
</div>