config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root 'homes#top'
  get 'homes/ranking' => 'homes#ranking'
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
  end
  resources :dogs
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :follows_index, on: :member
  end
  get 'search' => "searches#search"
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
  <footer class="footer_sign_in">
    <div class="container">
      <ul class="footer-ul">
        <li class="footer-li">
          <%= link_to root_path do %>
            <%= image_tag('footer-home.png',class: 'btn logo') %>
          <% end %>
        </li>
        <li class="footer-li">
          <%= link_to new_dog_path do %>
            <%= image_tag('dog.png',class: 'btn logo1') %>
          <% end %>
        </li>
        <li class="footer-li">
          <%= link_to new_article_path do %>
            <%= image_tag('post.png',class: 'btn logo1') %>
          <% end %>
        </li>
        <li class="footer-li">
          <span id="back">
            <a href="#">
              <%= image_tag('up.png',class: 'btn logo1') %>
            </a>
          </span>
        </li>
      </ul>
    </div>
  </footer>
<% else %>
  <footer class="footer_sign_out"></footer>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#ffffff;">
    <div class="container">
      <%= link_to root_path, class: 'btn nav-link text-light' do %>
        <h2 class="title">ONE DAYS</h2>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto ">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to ' ユーザー一覧',users_path, class: 'btn btn-square-raised-admin' %></li>
              <li><%= link_to ' 犬一覧',dogs_path, class: 'btn btn-square-raised-admin' %></li>
              <li><%= link_to ' 投稿一覧',articles_path, class: 'btn btn-square-raised-admin' %></li>
              <li><%= link_to ' ランキング',homes_ranking_path, class: 'btn btn-square-raised-admin'%></li>
              <li><%= link_to ' マイページ',user_path(current_user), class: 'btn btn-square-raised-admin' %></li>
              <li><%= link_to ' ログアウト',destroy_user_session_path, method: :delete , class: 'btn btn-square-raised-admin' %></li>
            <% else %>
              <li><%= link_to ' ランキング',homes_ranking_path, class: 'btn btn-square-raised' %></li>
              <li><%= link_to ' 投稿一覧',articles_path, class: 'btn btn btn-square-raised' %></li>
              <li><%= link_to ' ユーザー一覧',users_path, class: 'btn btn-square-raised' %></li>
              <li><%= link_to ' 犬一覧', dogs_path, class: 'btn btn-square-raised' %></li>
              <li><%= link_to ' マイページ',user_path(current_user), class: 'btn btn-square-raised' %></li>
              <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete , class: 'btn btn-square-raised' %></li>
            <% end %>
          <% else %>
            <li><%= link_to ' 新規登録', new_user_registration_path, class: 'btn btn-square-raised' %></li>
            <li><%= link_to ' ログイン', new_user_session_path, class: 'btn btn-square-raised' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search text-right">
  <% if user_signed_in? %>
    <%= form_with url:search_path, method: :get, local: :true do |f| %>
      <%= f.select :range, options_for_select([['ユーザー'],['犬'],['投稿']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward-match"],["後方一致","backword_match"],["部分一致","partial_match"]]) %>
      <div>
        <%= f.text_field :word %>
        <%= f.submit "検索" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneDays</title>
     <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "slick.css" %>
    <%= stylesheet_link_tag "slick-theme.css" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= render 'layouts/search' %>
      <%= yield %>
      <%= javascript_include_tag 'slick.js', 'data-turbolinks-track': 'reload' %>
      <script>
        $(document).ready(function(){
          $('.slider').slick({
            autoplay:true, // 自動再生を設定
            autoplaySpeed:3000, // スライド切り替えの時間を設定
            dots: true
          });
        });
      </script>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>